CREATE OR REPLACE PIPE OPENSKY_DB.BRONZE.AIRCRAFTS_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO OPENSKY_DB.BRONZE.AIRCRAFTS (
    ICAO24, FOUND, TYPE, ICAO_TYPE, MANUFACTURER, REGISTRATION,
    REGISTERED_OWNER, REGISTERED_OWNER_COUNTRY, FETCHED_AT, _LOADED_AT
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, TO_TIMESTAMP_NTZ($9, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), CURRENT_TIMESTAMP()
    FROM @OPENSKY_DB.BRONZE.LANDING/aircrafts/
)
FILE_FORMAT = (FORMAT_NAME = OPENSKY_DB.BRONZE.CSV_FORMAT);
