CREATE OR REPLACE PIPE OPENSKY_DB.BRONZE.AIRLINES_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO OPENSKY_DB.BRONZE.AIRLINES (
    ICAO, IATA, NAME, COUNTRY, CALLSIGN, _LOADED_AT
)
FROM (
    SELECT $1, $2, $3, $4, $5, CURRENT_TIMESTAMP()
    FROM @OPENSKY_DB.BRONZE.LANDING/airlines/
)
FILE_FORMAT = (FORMAT_NAME = OPENSKY_DB.BRONZE.CSV_FORMAT);
