CREATE OR REPLACE PIPE OPENSKY_DB.BRONZE.AIRPORTS_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO OPENSKY_DB.BRONZE.AIRPORTS (
    ICAO, IATA, NAME, COUNTRY, LAT, LON, _LOADED_AT
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP()
    FROM @OPENSKY_DB.BRONZE.LANDING/airports/
)
FILE_FORMAT = (FORMAT_NAME = OPENSKY_DB.BRONZE.CSV_FORMAT);
