CREATE OR REPLACE PIPE OPENSKY_DB.BRONZE.CALLSIGNS_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO OPENSKY_DB.BRONZE.CALLSIGNS (
    CALLSIGN, FOUND, CALLSIGN_ICAO, CALLSIGN_IATA,
    AIRLINE_ICAO, AIRLINE_IATA, AIRLINE_NAME, AIRLINE_COUNTRY, AIRLINE_CALLSIGN,
    ORIGIN_ICAO, ORIGIN_IATA, ORIGIN_NAME, ORIGIN_COUNTRY, ORIGIN_LAT, ORIGIN_LON,
    DESTINATION_ICAO, DESTINATION_IATA, DESTINATION_NAME, DESTINATION_COUNTRY,
    DESTINATION_LAT, DESTINATION_LON, FETCHED_AT, _LOADED_AT
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
           $16, $17, $18, $19, $20, $21, TO_TIMESTAMP_NTZ($22, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), CURRENT_TIMESTAMP()
    FROM @OPENSKY_DB.BRONZE.LANDING/callsigns/
)
FILE_FORMAT = (FORMAT_NAME = OPENSKY_DB.BRONZE.CSV_FORMAT);
