CREATE OR REPLACE PIPE OPENSKY_DB.BRONZE.FLIGHTS_RAW_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO OPENSKY_DB.BRONZE.FLIGHTS_RAW (
    ICAO24, CALLSIGN, ESTDEPARTUREAIRPORT, ESTARRIVALAIRPORT, FIRSTSEEN, LASTSEEN,
    ESTDEPARTUREAIRPORTHORIZDISTANCE, ESTDEPARTUREAIRPORTVERTDISTANCE,
    ESTARRIVALAIRPORTHORIZDISTANCE, ESTARRIVALAIRPORTVERTDISTANCE,
    DEPARTUREAIRPORTCANDIDATESCOUNT, ARRIVALAIRPORTCANDIDATESCOUNT,
    QUERIED_AIRPORT, MOVEMENT_TYPE, FETCHED_AT, _LOADED_AT
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
           TO_TIMESTAMP_NTZ($15, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), CURRENT_TIMESTAMP()
    FROM @OPENSKY_DB.BRONZE.LANDING/flights_raw/
)
FILE_FORMAT = (FORMAT_NAME = OPENSKY_DB.BRONZE.CSV_FORMAT);
