-- Landing (Bronze) objects for OpenSky ingestion in Snowflake. Idempotent - safe to re-run.

CREATE DATABASE IF NOT EXISTS OPENSKY_DB;

CREATE SCHEMA IF NOT EXISTS OPENSKY_DB.BRONZE;

-- Smallest size, auto-suspend/resume so it's not billed while idle.
CREATE WAREHOUSE IF NOT EXISTS OPENSKY_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- CSV shape shared by every table's file (header row, "" -> NULL).
CREATE FILE FORMAT IF NOT EXISTS OPENSKY_DB.BRONZE.CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('');

-- Internal stage: load_to_snowflake.py PUTs CSVs here (one subfolder per table).
CREATE STAGE IF NOT EXISTS OPENSKY_DB.BRONZE.LANDING
    FILE_FORMAT = OPENSKY_DB.BRONZE.CSV_FORMAT;

-- Departures + arrivals share one table, split by movement_type.
CREATE TABLE IF NOT EXISTS OPENSKY_DB.BRONZE.FLIGHTS_RAW (
    ICAO24 VARCHAR,
    CALLSIGN VARCHAR,
    ESTDEPARTUREAIRPORT VARCHAR,
    ESTARRIVALAIRPORT VARCHAR,
    FIRSTSEEN NUMBER,
    LASTSEEN NUMBER,
    ESTDEPARTUREAIRPORTHORIZDISTANCE NUMBER,
    ESTDEPARTUREAIRPORTVERTDISTANCE NUMBER,
    ESTARRIVALAIRPORTHORIZDISTANCE NUMBER,
    ESTARRIVALAIRPORTVERTDISTANCE NUMBER,
    DEPARTUREAIRPORTCANDIDATESCOUNT NUMBER,
    ARRIVALAIRPORTCANDIDATESCOUNT NUMBER,
    QUERIED_AIRPORT VARCHAR,
    MOVEMENT_TYPE VARCHAR,
    FETCHED_AT TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ
);

-- adsbdb.com enrichment landing tables - columns match ingest_adsbdb.py's CALLSIGN_COLUMNS.
CREATE TABLE IF NOT EXISTS OPENSKY_DB.BRONZE.CALLSIGNS (
    CALLSIGN VARCHAR,
    FOUND BOOLEAN,
    CALLSIGN_ICAO VARCHAR,
    CALLSIGN_IATA VARCHAR,
    AIRLINE_ICAO VARCHAR,
    AIRLINE_IATA VARCHAR,
    AIRLINE_NAME VARCHAR,
    AIRLINE_COUNTRY VARCHAR,
    AIRLINE_CALLSIGN VARCHAR,
    ORIGIN_ICAO VARCHAR,
    ORIGIN_IATA VARCHAR,
    ORIGIN_NAME VARCHAR,
    ORIGIN_COUNTRY VARCHAR,
    ORIGIN_LAT FLOAT,
    ORIGIN_LON FLOAT,
    DESTINATION_ICAO VARCHAR,
    DESTINATION_IATA VARCHAR,
    DESTINATION_NAME VARCHAR,
    DESTINATION_COUNTRY VARCHAR,
    DESTINATION_LAT FLOAT,
    DESTINATION_LON FLOAT,
    FETCHED_AT TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ
);

-- Matches ingest_adsbdb.py's AIRLINE_COLUMNS - derived from callsigns, not a separate API call.
CREATE TABLE IF NOT EXISTS OPENSKY_DB.BRONZE.AIRLINES (
    ICAO VARCHAR,
    IATA VARCHAR,
    NAME VARCHAR,
    COUNTRY VARCHAR,
    CALLSIGN VARCHAR,
    _LOADED_AT TIMESTAMP_NTZ
);

-- Matches ingest_adsbdb.py's AIRPORT_COLUMNS - derived from callsigns, not a separate API call.
CREATE TABLE IF NOT EXISTS OPENSKY_DB.BRONZE.AIRPORTS (
    ICAO VARCHAR,
    IATA VARCHAR,
    NAME VARCHAR,
    COUNTRY VARCHAR,
    LAT FLOAT,
    LON FLOAT,
    _LOADED_AT TIMESTAMP_NTZ
);

-- Matches ingest_adsbdb.py's AIRCRAFT_COLUMNS - only populated via ingest_adsbdb.py --aircraft.
CREATE TABLE IF NOT EXISTS OPENSKY_DB.BRONZE.AIRCRAFTS (
    ICAO24 VARCHAR,
    FOUND BOOLEAN,
    TYPE VARCHAR,
    ICAO_TYPE VARCHAR,
    MANUFACTURER VARCHAR,
    REGISTRATION VARCHAR,
    REGISTERED_OWNER VARCHAR,
    REGISTERED_OWNER_COUNTRY VARCHAR,
    FETCHED_AT TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ
);
